# Generated by Django 3.2.7 on 2021-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wb_token',
            field=models.CharField(max_length=256),
        ),
    ]
