# Generated by Django 3.2.7 on 2021-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Вб pid'),
        ),
        migrations.AddField(
            model_name='order',
            name='wb_order_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Вб order_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='proceeds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Прибыль'),
        ),
    ]
